### ISSUE TITLE
Can't add Blocks to PYTHONPATH after namespace packages are on

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks#696] opened 2015-06-03 09:48 UTC
Subject. After #693 I can't import Blocks from PYTHONPATH. Commenting the line https://github.com/mila-udem/blocks/blob/master/blocks/__init__.py#L4 fixes the issue.

Is it expected?

**Comment by bartvm** [comment] 2015-06-03 12:35
What do you mean with "I can't import Blocks from PYTHONPATH"?

**Comment by bartvm** [comment] 2015-06-03 12:39
Oh wait, I think I got what you mean. Yes, that's expected behaviour. You need to install Blocks in editable mode (`pip install -e .`).

**Comment by rizar** [comment] 2015-06-03 14:43
I mean that when explicitly add the path to the desired checkout of Blocks to the PYTHONPATH, it is ignored and the installed copy is imported.

`pip install -e` is kind of bad because only it is a global setting and I would like to quickly switch from one version of Blocks to another. I anticipate your advice will be to use virtual environments, am I right?

**Comment by bartvm** [comment] 2015-06-03 14:53
How is it a global setting? `pip install -e .` has the same effect as adding it to your `PYTHONPATH` i.e. if you switch branches or modify the code, that's immediately reflected.

**Comment by bartvm** [comment] 2015-06-03 14:56
Too fast again. You're saying you have both an installed version, but you want the `PYTHONPATH` to precede the installed version? That won't work for namespace packages I guess. I just have one version of Blocks, installed in editable mode. What's the advantage of having an installed version *and* a different version on your `PYTHONPATH`?

**Comment by rizar** [comment] 2015-06-03 16:25
My workflow typically involves a hacked Blocks fork specific to the project I currently do and a repo tracking master, in which I do PRs and test other people PRs. I want to be able to switch from one to another in one shell without influencing other ones. `pip install -e` is not good in this situation because it can not be overriden with `$PYTHONPATH`. That's why I typically have regularly reinstall (without `-e`) from the master fork and change `$PYTHONPATH` to use the hacked one.

My problem will be not that rare I guess, so best practices should be described in this issue to refer people here. Do you think using virtual environments is a good idea?

**Comment by bartvm** [comment] 2015-06-03 16:43
Yeah, if you want work with several versions of a single package at the same time, then virtual environments would be the standard solution.

**Comment by rizar** [comment] 2015-06-03 16:44
Thanks, I will try that, and let's keep the ticket open until I make sure that it does the job.

**Comment by dwf** [comment] 2015-06-03 16:48
I prefer conda environments myself, but to each his own.

Obligatory:
![](https://i.imgur.com/YbXU6e7.jpg)

**Comment by bartvm** [comment] 2015-06-03 16:51
Docs: http://conda.pydata.org/docs/test-drive.html#managing-environments

If you stick with `virtualenv`, have a look at `virtualenvwrapper` and `autoenv`: http://docs.python-guide.org/en/latest/dev/virtualenvs/#virtualenvwrapper

**Comment by rizar** [comment] 2015-06-19 15:20
I read a bit about virtual environments and I found it a way heavier solution then simply then overriding the installed package with the PYTHONPATH.

That being said, I am joining camp of namespace-package sceptics. Does the difference between `from blocks.extras import ... ` and `from blocks_extras import ...` really matter?

**Comment by janchorowski** [comment] 2015-06-23 19:40
Hi,

I am sceptical about this change too (just bit me in the posterior while trying to use some Dima's code with an overridden Blocks). I guess we should lower the barrier of entry into using blocks, keeping in mind that not everyone is fully up-to-date with advanced aspects of Python. 

Blocks is a specialized fast-changing library, whose users are likely to keep their own modified versions and will want to update it more often than the core Python environment. Thus, we should make it easy to override whatever is installed.

**Comment by rizar** [comment] 2015-06-25 04:42
Seems like @bartvm is not around. @dwf , @vdumoulin , @janchorowski , @dmitriy-serdyuk , what do you guys all think about switching to two separate packages instead of namespace ones? If we all don't like it, I think we can proceed to removing this feature without Bart's approve.

**Comment by dwf** [comment] 2015-06-25 04:55
@bartvm told me he is on vacation.

I am indifferent with a slight lean towards negative on namespace packages. The proposal in [PEP 0420](https://www.python.org/dev/peps/pep-0420/) makes them a lot nicer, but the Python 2.x-compatible namespace packages are a pain.

However, I don't think that you should necessarily expect to rely on `PYTHONPATH` hacks indefinitely (and putting your fork directory on `PYTHONPATH` is indeed a hack). For example, there are definitely things that should be added to Fuel that will involve compiled code for speed, code that will not function correctly unless at least built in-place with `python setup.py build_ext --inplace`. Installing as a package (even in editable mode, inside a virtualenv or conda env) is in some ways cleaner than relying on something on the `PYTHONPATH`.

**Comment by dmitriy-serdyuk** [comment] 2015-06-25 23:39
It seems that python doesn't fully follow the Linux way. I've always thought that environmental variables are made to change one's environment, but python has it's own predefined paths before it loads packages from PYTHONPATH.

So I just didn't install blocks and other packages which I need to change frequently and added them into PYTHONPATH manually. I didn't have any problems with namespace packages and they look very neat.

**Comment by lamblin** [comment] 2015-06-26 21:08
Like @dwf, I don't really have an opinion on namespace packages, but I feel that once a package is complex enough that it has dependencies checked at install, and scripts to install in the `PATH`, we should rely on installing the package with `setup.py` or one of the python tools, rather than manually modifying `PYTHONPATH`.

**Comment by rizar** [comment] 2015-06-29 10:46
What you are saying guys is right, but it's just so simple to add a bunch of packages to PYTHONPATH, that I expect many users to use this option. Not all in deep learning community are good at Python, as @janchorowski rightly mentioned. 

But given this variety of opinion, let's wait and see if namespace packages will bring us more troubles than  this PYTHONPATH one.

**Comment by rizar** [comment] 2015-07-04 19:32
The quirk number two: it is not possible to install Blocks-extras in the usual mode and Blocks in editable mode.

**Comment by janchorowski** [comment] 2015-07-06 06:35
At least this one is documented.

Dmitry Bogdanov wrote:

**Comment by rizar** [comment] 2015-08-14 06:05
And people keep hitting problems with namespace packages ... https://github.com/mila-udem/blocks-extras/issues/21

**Comment by ASalvail** [comment] 2015-08-14 15:49
Given that the initial point of namespace packages are to make the import path a little more user friendly. However it seems to fall short of that goal with all the problems it introduces. 
Now, if you consider that @dwf has an image specifically to make fun of namespace packages problems, I guess it gives you a clue that it might be better to have two separate packages, at least until namespace packages get some more support from tools.

**Comment by dmitriy-serdyuk** [comment] 2016-05-09 19:31
This should be fixed, since we don't use namespace packages anymore.

**Closed** 2016-05-09 19:33 UTC
Labels: bug, discussion
