### ISSUE TITLE
Unable to see live plotting

### ISSUE THREAD

**Issue by jrabary** [mila-udem/blocks#715] opened 2015-06-10 07:53 UTC
Dear all,

Sorry for posting this here as issue here but I don't know where else I can report this problem. I'm trying to reproduce the live plotting example in the documentation. The example runs perfectly but I can't see the plot in the web page. There's something running in the console of the web browser when I run the python blocks example, but the page remains blank. Is it a problem related with blocks Plot or with Bokeh ?

Best,

Jao

**Comment by FranciscoCanas** [comment] 2015-06-10 18:37
I had the same problem, and eventually realized that the issue is with the CSS/JS on the bokeh page: Clicking on the name of your plot won't expand the div as it should, so you may need to use an element selector to find the exact div, and remove the .collapse property from its style sheet.

I think it's related to this:
https://github.com/bokeh/bokeh/issues/2290

**Comment by sotelo** [comment] 2015-06-11 16:09
Funny enough, I tried the bokeh plotting in 2 computers and it didn't work on one. However, Francisco's solution works. Thanks!

(Although it's kind of uncomfortable to do this every time.)

**Comment by rizar** [comment] 2015-06-12 22:22
Since this is not a Blocks issue, I am closing it.

**Closed by rizar** 2015-06-12 22:22 UTC
