### ISSUE TITLE
bokeh-server command no longer exists 

### ISSUE THREAD

**Issue by dbikard** [mila-udem/blocks#1081] opened 2016-05-11 10:43 UTC
The new version of bokeh no longer has the bokeh-server command. Could you update the documentation to reflect this change? What is now the proper way to run bokeh in order to do live plotting? I tried to simply run "bokeh serve", but then my blocks script return the following error:
"Bokeh required for Plot extension"

Thanks for your help!

**Comment by dwf** [comment] 2016-05-11 17:09
So far the extension hasn't been updated for lack of programmer resources. There really isn't any "dashboard"-like functionality that displays all plots & documents the way bokeh-server used to by default, so we'd have to actually write one. Right now the fix is to stick to bokeh-0.10.

Closing as duplicate of mila-udem/blocks-extras#35 (which you can follow for updates if you like).

**Closed by dwf** 2016-05-11 17:09 UTC
