### ISSUE TITLE
get predictions from blocks?

### ISSUE THREAD

**Issue by sandeepsoni** [mila-udem/blocks#1095] opened 2016-05-26 17:55 UTC
Its not clear in the documentation on how to obtain the predictions from blocks. My scenario is that I want to train a multilayer perceptron, but after training I don't want just the error rate for the test data (as can be done easily using mainloop and monitoring), but also the predictions made by the learned model on the test data. How do I get the predictions?

I tried ```get_snapshot``` method, but I don't know if that's the correct way to get the predictions on test data.

**Comment by dmitriy-serdyuk** [comment] 2016-05-26 18:03
Please search existing issues before creating a new one, it's a duplicate of #1033 .

Blocks works with Theano variables, so it's straightforward to compile a function, iterate over your test set and get the predictions. Other way is described in #1033: you can extend the monitoring extension.

**Closed by dmitriy-serdyuk** 2016-05-26 18:03 UTC
